spring:
  data:
    mongodb:
      database: todak
      username: todak
      password: todak
      port: 27017
      host: 127.0.0.1

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug