spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: todak
    password: todak
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace