spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: todak
    password: todak
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: trace